### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Devil-panda** [Sna-aaa/qb-sna-vehiclekeys#5]
im using jonasdev99 qb-garages has it is working with radial menu and when see through your readme and find out about ``vehiclekeys:client:SetOwner``  i commet these but if player dont have key then also player can toggle engine and drive the vehicle

https://github.com/JonasDev99/qb-garages
^^^^ 
using thess garage

**Comment by Sna-aaa** [comment]
The garage doesn't change anything, it will not give the key as the player must have it in his inventory
