### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by LaserFeesh** [Sna-aaa/qb-sna-vehiclekeys#6]
Is there some way to be able to put the vehicle carjacking into this?  Right now taking a car from an NPC requires players to hotwire the car after killing the driver.

**Comment by Sna-aaa** [comment]
It is a choice to keep the code low and the resource fast
Exactly as in real life, as the motor always stops now and as you keep your key in your pocket, when the thief will get you out of the car, the car will not start and the hotwire is needed
