### ISSUE TITLE
When i spawn any vehicle 

### ISSUE THREAD

**Issue by MamBa-OP** [Sna-aaa/qb-sna-vehiclekeys#7]
![image](https://user-images.githubusercontent.com/69965743/214782246-4fa6d328-3905-44ed-bbd2-94c08f191201.png)

**Comment by Sna-aaa** [comment]
Rename my resource with another name than qb-vehiclekeys
It will go trough this change from qb-core

**Comment by MamBa-OP** [comment]
already renamed to qb-vehiclekeys but same issue

**Comment by Sna-aaa** [comment]
Exactly the name that you need to NOT use, try anything else

**Comment by MamBa-OP** [comment]
you mean i have not to use qb-vehiclekeys ? i have to something else

**Comment by Sna-aaa** [comment]
Ok found the problem, it seems that your qb-core is not updated to the last version
![image](https://user-images.githubusercontent.com/88613496/215695406-da486f3f-d543-4075-a4fc-39914a349d53.png)
Here you can see a test for the vehiclekeys, it is missing on your version normally

**Comment by MamBa-OP** [comment]
![image](https://user-images.githubusercontent.com/69965743/215709011-fef7ab8b-2378-4cae-a0e8-e4588cc7dcf6.png)
i have already the latest version of qbcore and all things

**Comment by Sna-aaa** [comment]
Ok i've updated the readme
With the last update of qbcore and the directory name, it is working nicely, i've installed it yesterday from a fresh qbcore
